version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.5.1
    working_directory: ~/pm_web
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: install dependencies 
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: run tests
          command: yarn test
  deploy:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Create Env file at Repository root
          command: |
            chmod +x scripts/create_env.sh && ./scripts/create_env.sh
      - run: 
          name: install dependencies 
          command: yarn install
      - run:
          name: Update APT sources list
          command: |
            sudo rm /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
            sudo apt-get update
      - run:
          name: Deploy application to environment
          command: |
            chmod +x scripts/deploy.sh && ./scripts/deploy.sh
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
                - develop
                - /(release|hotfix)\/v[0-9].[0-9].[0-9]/

